spring:
  application:
    name: kstream-events-router

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
    consumer:
      auto-offset-reset: earliest
    topics:
      inputTopic: input-events
      franceTopic: france-events
      spainTopic: spain-events
      otherTopic: other-events